kind: Service
apiVersion: v1
metadata:
  name: nginx
  labels:
    k8s-app: nginx
spec:
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 30151
    targetPort: 80
    port: 3000
  selector:
    k8s-app: nginx
