apiVersion: v1
kind: PersistentVolume
metadata:
  name: cicd-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 192.168.0.110
    path: /opt/nfs


---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cicd-pvc
  namespace: cicd
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteMany

