apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2021-12-18T14:22:22Z"
  name: cicd-sa-cluster
  resourceVersion: "1565332"
  uid: c345d22e-aba9-40f3-a1d7-9708e84d64f9
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: cicd-sa
  namespace: cicd
