apiVersion: apps/v1
kind: Deployment 
metadata:
  name: order
  namespace: ms 
spec:
  replicas: 1
  selector:
    matchLabels:
      project: ms
      app: order
  template:
    metadata:
      labels:
        project: ms 
        app: order
    spec:
      imagePullSecrets:
      - name: registry-pull-secret
      containers:
      - name: order
        image: harbor.justbeta.pro/ms/order:1.0
        imagePullPolicy: IfNotPresent 
        resources:       #资源申请限制
          requests:      #最低需求资源
            cpu: 0.12
            memory: 128Mi
          limits:       #限制最高资源
            cpu: 0.25 
            memory: 400Mi
        ports:
          - protocol: TCP
            containerPort: 8020 
        readinessProbe:
          tcpSocket:
            port: 8020
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8020
          initialDelaySeconds: 60
          periodSeconds: 10
