apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-http01
  namespace: default
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
     # Email address used for ACME registration
    email: shangxianjiang@gmail.com
    privateKeySecretRef:
      name: letsencrypt-http01-account-key
    solvers:
    - http01:
       ingress:
         class:  ingress-tomcat # 指定被自动修改的 Ingress 名称
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demon.justbeta.pro.tls
  namespace: cert-manager
spec:
  dnsNames:
  - demon.justbeta.pro # 要签发证书的域名
  issuerRef:
    kind: Issuer
    name: letsencrypt-http01 # 引用 Issuer，指示采用 http01 方式进行校验
  secretName: demon.justbeta.pro.tls # 最终签发出来的证书会保存在这个 Secret 里面