kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-provisioner
  namespace: default
spec:
  selector:
    matchLabels:
       app: nfs-provisioner
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-provisioner
    spec:
      serviceAccount: nfs-provisioner
      containers:
        - name: nfs-provisioner
          image: registry.cn-beijing.aliyuncs.com/mydlq/nfs-subdir-external-provisioner:v4.0.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: justbeta.money/nfs
            - name: NFS_SERVER
              value: 192.168.0.110
            - name: NFS_PATH
              value: /opt/nfs 
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.0.110
            path: /opt/nfs
