apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-read
  namespace: rbac
rules:
  - verbs:
      - "*"
    resourceNames:
      - ""
    resources:
      - ""
    apiGroups: 
      - ""